
### fasd ###
- name: fasd | clone repo
  tags: fasd
  set_fact: fasd_repo='{{fasd_repo | default(fasd.repo)}}'

- name: fasd | create necessary dirs
  tags: fasd
  file: path={{item}} state=directory
  with_items:
    - "{{ fasd_repo }}"
    - ~/.local/share/man/man1

- debug: msg='fasd clone {{fasd_repo}}'   #'
  tags: fasd

- name: fasd | clone
  tags: fasd
  git: repo={{fasd_repo}} dest={{fasd.dest}}

- name: fasd | make install
  tags: fasd
  shell: >
    PREFIX=$HOME make install;
    mv ~/share/man/man1/fasd.1 ~/.local/share/man/man1;
    find ~/share/ -type d -empty -delete;
  args:
    chdir: "{{fasd.dest}}"
    executable: /bin/bash
